### ISSUE TITLE
How do we connect to our respective databases?

### ISSUE THREAD

**Issue by EVE0817** [2020-GPW-L5K2-C/Chengdu-Bus-Company#17]
We can only share code in GitHub. But databases are different. How to connect the contents of different databases?  @jslemmer

**Comment by EVE0817** [comment]
How do we connect our respective databases together?

**Comment by 9sa6c** [comment]
You can just use one database. By using one of the students database, all your code can connect to the same database.

You can also use one environment (choose from one of your groups team members) to upload all your code as well.
