### ISSUE TITLE
About demand analysis

### ISSUE THREAD

**Issue by EVE0817** [2020-GPW-L5K2-C/Chengdu-Bus-Company#5]
General users: bus route query, fare query
Administrator: car information management, driver information management, route management, user information management, reports
Anything else？

**Comment by EVE0817** [comment]
Do we need to make a payment system or just record the payment method? @jslemmer

**Comment by 9sa6c** [comment]
No real payment is needed, you can just record the payment. But do include a page where the "payment" is being made. So sort of a "fake" page where you can record the payment.
